
spring:
  mail:
    host: smtp.gmail.com
    username: hackmalli2020@gmail.com
    password: meyacucmrraayazl
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true